In [1]:
import numpy as np

In [5]:
#1 Maximum value in the matrix
mtx = np.matrix('[1,2,3;4,5,6;7,8,9]')
mtx.max()

9

In [7]:
#2 Minimum value in the matrix
mtx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mtx.min()

1

In [10]:
#3 No of rows and columns in the matrix
mtx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mtx.shape

(3, 3)

In [21]:
#4 Select the elements from a given matrix
mtx = np.array([[1,2,3],[4,5,6],[7,8,9]])
mtx.take(3)

4

In [12]:
#5 Sum of values in the matrix
mtx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mtx.sum()

45

In [15]:
#6 Sum of diagonal elements
mtx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
value = np.diagonal(mtx)
value.sum()

15

In [26]:
#7 Add/Sub in matrix
mtx1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mtx2 = np.matrix([[9,8,7],[6,5,4],[3,2,1]])
addmtx = np.add(mtx1, mtx2)
submtx = np.subtract(mtx1, mtx2)
print(addmtx)
print(submtx)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [41]:
#8 Add rows/columns to the matrix
mtx1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mtx2 = np.array([[4],[7],[0]])
mtx3 = np.array([4,7,0])
arr1 = np.hstack([mtx1, mtx2])
print(arr1)
arr2 = np.vstack([mtx1, mtx3])
print(arr2)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 7 0]]


In [53]:
#9 Matrix Multiplication 
mtx1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mtx2 = np.matrix([[0],[7],[4]])
value = np.matmul(mtx1, mtx2)
value

matrix([[26],
        [59],
        [92]])

In [58]:
#10 Eigen Value
mtx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
value = np.linalg.eigvals(mtx)
value

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [59]:
#11 Determinant of matrix
mtx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
value = np.linalg.det(mtx)
value

0.0

In [62]:
*#12 Inverse a matrix
mtx = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.inv(mtx))

LinAlgError: Singular matrix

In [74]:
#13 Frequency and Unique values in array
mtx = np.array([[1,2,1],[3,2,4],[3,2,1]])
uni, fre = np.unique(mtx, return_counts=True)
print(uni, fre)

[1 2 3 4] [3 3 2 1]


In [76]:
#14 Matrix multiply (Complex no)
mtx1 = np.array([[1+9j, 2+8j], [3+7j, 4+6j]])
mtx2 = np.array([[9+1j, 8+2j], [7+3j, 6+4j]])
value = np.vdot(mtx1, mtx2)
value

(140-200j)

In [80]:
#15, #16 Inner & Outer Product of two matrix
mtx1 = np.array([1,2,3])
mtx2 = np.array([7,8,9])
mtx3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mtx4 = np.array([[9,8,7],[6,5,4],[3,2,1]])
value1 = np.outer(mtx1, mtx2)
value3 = np.outer(mtx3, mtx4)
print(value1)
print(value3)
value2 = np.inner(mtx1, mtx2)
value4 = np.inner(mtx3, mtx4)
print(value2)
print(value4)

[[ 7  8  9]
 [14 16 18]
 [21 24 27]]
[[ 9  8  7  6  5  4  3  2  1]
 [18 16 14 12 10  8  6  4  2]
 [27 24 21 18 15 12  9  6  3]
 [36 32 28 24 20 16 12  8  4]
 [45 40 35 30 25 20 15 10  5]
 [54 48 42 36 30 24 18 12  6]
 [63 56 49 42 35 28 21 14  7]
 [72 64 56 48 40 32 24 16  8]
 [81 72 63 54 45 36 27 18  9]]
50
[[ 46  28  10]
 [118  73  28]
 [190 118  46]]


In [81]:
#17 Covariance Matrix
mtx1 = np.matrix([[1,2],[3,4]])
mtx2 = np.matrix([[5,6],[7,8]])
value = np.cov(mtx1, mtx2)
value

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [ ]:
#18 Covariance matrix to correlation matrix

In [67]:
#19 Kronecker Product
mtx1 = np.matrix([[1,2],[3,4]])
mtx2 = np.matrix([[5,6],[7,8]])
kpmtx = np.kron(mtx1, mtx2)
[[5*1, 6*1, 5*2, 6*2],
 [7*1, 8*1, 7*2, 8*2],
 [5*3, 6*3, 5*4, 6*4],
 [7*3, 8*3, 7*4, 8*4]]
kpmtx

matrix([[ 5,  6, 10, 12],
        [ 7,  8, 14, 16],
        [15, 18, 20, 24],
        [21, 24, 28, 32]])

In [65]:
#20 Matrix to list
mtx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
value = mtx.tolist()
value

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]