In [77]:
import numpy as np

In [3]:
#1 Replace elements that didnt statisfy the condition
arr = np.array([1,2,3,7,8,9])
arr[arr>5] = 4
arr

array([1, 2, 3, 4, 4, 4])

In [6]:
#2 Return indices of elements that statisfy the condition
arr = np.array([55,34,56,87,24,21])
np.where(arr>50)

(array([0, 2, 3], dtype=int64),)

In [39]:
#3 Replace NaN values with avg of columns
arr = np.array([[1,2,3],[4,np.NaN,5],[6,7,np.NaN]])
arr2 = np.nanmean(arr, axis=0)
ind = np.where(np.isnan(arr))
arr[ind] = np.take(arr2, ind[1])
arr

array([[1. , 2. , 3. ],
       [4. , 4.5, 5. ],
       [6. , 7. , 4. ]])

In [11]:
#4 Replace negative values with zero 
arr = np.array([[-1,2,-3],[4,-5,6],[-7,8,-9]])
arr[arr<0]=0
arr

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

In [87]:
#5 Values of certain index positions
arr1 = np.array([1,2,5,6,9])
arr2 = np.array([3,7,0])
arr1.put([1,3], arr2)
arr1

array([1, 3, 5, 7, 9])

In [25]:
#6 Find index where element is zero
arr = np.array([[0,1,0],[2,0,3]])
np.argwhere(arr==0)

array([[0, 0],
       [0, 2],
       [1, 1]], dtype=int64)

In [57]:
#7 Remove columns that contain non-numeric values
arr = np.array([[1,2,3],[4,np.NaN,5],[6,7,np.NaN]])
arr[:,~np.isnan(arr).any(axis=0)]

array([[1.],
       [4.],
       [6.]])

In [44]:
#8 Access diff rows
arr = np.array([[101,20,3,10],[40,5,66,7],[70,88,9,141]])
arr[[1]]
arr2 = np.array([[1,20,3,1],[40,5,66,7],[70,88,9,11],[80,100,50,77]])
arr2[[1,2,3]]
arr3 = np.array([[[10,25,60],[30,45,55],[20,45,7]],[[50,65,8],[70,85,10],[11,22,33]]])
arr3[[0,1],[1,1]]


array([[30, 45, 55],
       [70, 85, 10]])

In [62]:
#9 Get row no having element larger than x
arr = np.array([[1,2,3,4,5],[10,-3,30,4,5],[3,2,5,-4,5],[9,7,3,6,5]])
np.where(np.any(arr>6, axis=1))

(array([1, 3], dtype=int64),)

In [85]:
#10 Fill the diagonals 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.fill_diagonal(arr, 0)
arr

array([[0, 2, 3],
       [4, 0, 6],
       [7, 8, 0]])

In [82]:
#11 Check elements present
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([2,5,8])
np.isin(arr1, arr2)

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [80]:
#12 Combined array index by index
arr1 = np.array([[1,3,5],[7,9,1]])
arr2 = np.array([[2,4,6],[8,0,2]])
np.dstack((arr1, arr2))

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 0],
        [1, 2]]])