In [1]:
import numpy as np

In [4]:
#1 Empty Array
np.empty((3,2), dtype=int)

array([[ 538976288, 1835891059],
       [1769108581, 1752637539],
       [1612738149, 1763729507]])

In [12]:
#1 Full Array
np.full((3,2), 7, dtype=int)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [8]:
#2 Array filled with zeros
np.zeros((9,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
#3 Array filled with ones
np.ones((4,9), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
#4 Array contains a specific row
a = np.random.randint(1,10, size=[4,8])
b = a[3,:]
b

array([3, 3, 4, 6, 5, 1, 7, 5])

In [67]:
#5 Remove rows containing non-numeric values
a = np.array([[2,3,4,5], [6,7,8,9], [1,np.nan,np.nan,0]]) 
b = a[~np.isnan(a).any(axis=1)]
b

array([2., 3., 4., 5., 6., 7., 8., 9., 1., 0.])

In [44]:
#6 Remove single dimensional entries from an matrix
a = np.array([[[2,3,4,5], [6,7,8,9]]])
a.shape
b = np.squeeze(a)
b.shape

(2, 4)

In [54]:
#7 No  of occurrences of a sequence
a = np.array([[1,2,3,4],[5,6,3,4],[7,8,3,4],[9,0,3,4]])
b = repr(a).count("3, 4")
b

5

In [56]:
#8 Most frequent value
a = np.array([1,2,1,3,1,4,1,5])
b = np.bincount(a).argmax()
b

1

In [66]:
#9 Combining a 1d and 2d array
a = np.arange(9)
b = np.arange(36).reshape(4,9)
for a,b in np.nditer([a, b]):
    print(a,":",b)

0 : 0
1 : 1
2 : 2
3 : 3
4 : 4
5 : 5
6 : 6
7 : 7
8 : 8
0 : 9
1 : 10
2 : 11
3 : 12
4 : 13
5 : 14
6 : 15
7 : 16
8 : 17
0 : 18
1 : 19
2 : 20
3 : 21
4 : 22
5 : 23
6 : 24
7 : 25
8 : 26
0 : 27
1 : 28
2 : 29
3 : 30
4 : 31
5 : 32
6 : 33
7 : 34
8 : 35


In [75]:
#10 All combinations of two arrays
arr1 = np.array([1,2])
arr2 = np.array([4,6])
comb = np.array(np.meshgrid(arr1, arr2)).T.reshape(-1,2)
comb

array([[1, 4],
       [1, 6],
       [2, 4],
       [2, 6]])

In [83]:
#11 Border around an array
a = np.zeros((5,7))
a[1:4, 1:6] = 1
print (a)
b = np.ones((2,2))
b = np.pad(b, pad_width=1, mode='constant', constant_values=0)
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [90]:
#12 Compare two arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arrg = np.greater(arr1, arr2)
print(arrg)
arrl = np.less(arr1, arr2)
print(arrl)
arre = np.array_equal(arr1, arr2)
print(arre)

[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
False


In [91]:
#13 Check for specific values in an array
arr1 = np.array([[1,2],[3,4]])
3 in arr1

True

In [ ]:
#14 2d diagonals of 3d array


In [93]:
#15,16 Flatten a matrix
arr = np.arange(16).reshape(2,4,2)
arrf = arr.flatten()
arrf

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [104]:
*#17 Move axes of an array to new position
arr = np.arange(16)
print(arr)
arrp = np.moveaxis(arr, 0, -1)
print(arrp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [112]:
#18 Interchange two axes
arr1 = np.arange(16).reshape(4,4)
print(arr1)
arrs1 = np.swapaxes(arr1, 0, 1)
print(arrs1)
arr2 = np.arange(16).reshape(2,4,2)
print(arr2)
arrs2 = np.swapaxes(arr2, 1, 2)
print(arrs2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
[[[ 0  2  4  6]
  [ 1  3  5  7]]

 [[ 8 10 12 14]
  [ 9 11 13 15]]]


In [ ]:
#19 Fibonacci Series


In [116]:
#20 Count no of non-zero values
arr = np.arange(16).reshape(4,4)
value = np.count_nonzero(arr)
value

15

In [124]:
#21 No of elements for a given axis
arr = np.arange(8).reshape(1,4,2)
value = np.size(arr, 1)
value

4

In [127]:
#22 Trim the leading/trailing zeros
arr = np.array([0,0,0,1,2,3,0,0,0])
value = np.trim_zeros(arr, 'b')
value

array([0, 0, 0, 1, 2, 3])

In [134]:
#23 Change datatype
arr = np.arange(16).reshape(4,4)
arr = arr.astype('float64')
arr.dtype

dtype('float64')

In [140]:
#24 Reverse an array
arr = np.arange(8)
value = np.flip(arr)
value

array([7, 6, 5, 4, 3, 2, 1, 0])

In [141]:
#25 Read-Only Array
arr = np.arange(8)
arr.setflags(write=False)
arr[6]=0

ValueError: assignment destination is read-only